`##sys#find-files' bug fix: handle dot files recursively
Assuming:

    $ mkdir -p foo/bar/.baz

Old behavior:

  $ csi -e '(use posix) (print (find-files "foo" dotfiles: #t))'
  (foo/bar)

Behavior with this patch:

  $ csi -e '(use posix) (print (find-files "foo" dotfiles: #t))'
 (foo/bar/.baz foo/bar)

Without this patch, delete-directory doesn't properly honor the
`recursive' optional argument:

  $ csi -e '(use posix) (delete-directory "foo" #t)'

  Error: (delete-directory) cannot delete directory - Directory not empty: "foo/bar"

Signed-off-by: Christian Kellermann <ckeen@pestilenz.org>