data-structures: fix substring-index[-ci] corner case ("" as 2nd arg)
Fix regression introduced by 25db851b90260:

$ ~/local/chicken-4.9.0.1/bin/csi -p '(substring-index "foo" "")'

$ ~/local/chicken-4.10.0rc1/bin/csi -p '(substring-index "foo" "")'

Error: (substring-index) out of range
0
0

        Call history:

        <syntax>          (substring-index "foo" "")
        <eval>    (substring-index "foo" "")    <--

Signed-off-by: Mario Domenech Goulart <mario.goulart@gmail.com>